### ISSUE TITLE
Is it possible to use this with Alloy Models?

### ISSUE THREAD

**Issue by jyounus** [dbankier/nano#12]
Hey there,

This might seem like a weird question (and one that kind of defeats the purposes as to why you wrote this library) but is it possible to use alloy models with this? 

What we basically want to do is achieve two-way binding but using the built in alloy models. We're currently using model with this SQL Rest Adapter: https://github.com/viezel/napp.alloy.adapter.restsql

We use alloy models for persistent storage and to download the data using the above adapter. Now we'd like to use two-way binding but passing in an alloy model for nano($, model); doesn't hook up anything. I'm guessing that's because to retrieve data from an alloy model (or backbone object), you have to do something like model.get("propertyName"); in order to do that.

I've tried it but no luck. The best I could get it to was model.toJSON() but obviously that's not going to keep the changes in-sync. I was wondering if you have any ideas if this could be achieved or if it's even currently possible/if it's planned to be supported?

Thanks! :)

**Comment by jyounus** [comment]
An example as to why you might want to do this would be a profile page. Download the relevant data using the linked SQL Rest Adapter, let alloy models handle the local storing of it and use nano for two-way binding with textfields.

**Comment by dbankier** [comment]
Alloy has it's own data binding for backbone models which is probably what you are looking for.
Don't think nano could do it as is, but it wouldn't be hard to create a plugin.

**Comment by jyounus** [comment]
Alloy does provide data binding however it's only one-way, we'd like to use nano and make it two-way.
Might look into it and create a plugin. Thanks.

**Comment by dbankier** [comment]
Yep, you're right. Tell how you go with plugin.
