### ISSUE TITLE
Package as module with Titaniumifier

### ISSUE THREAD

**Issue by FokkeZB** [dbankier/nano#2]
Why?

* Easier versioning
* Easier dependencies
* Easier distribution (manual zip + gitTio)

**Comment by dbankier** [comment]
Haven't looked at titaniumifier yet. Will have a look soon.

**Comment by yuchi** [comment]
Fantastic! Would you mind if add this module to a small showcase list on titaniumifier repo?

**Comment by dbankier** [comment]
go for it.

**Comment by yuchi** [comment]
Here it is: https://github.com/smclab/titaniumifier/wiki/Examples
