### ISSUE TITLE
Android errors

### ISSUE THREAD

**Issue by mpociot** [dbankier/nano#8]
Hi,

running your example code on Android produces a loop with these error:

```javascript
[WARN] :   IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
[WARN] :   IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
[WARN] :   IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
[WARN] :   IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
```

Also when manually changing the values of a textfield by typing in a new value, the text gets prepended.

Example:

Textfield value (in your example): `First`

On the keyboard type: `1`

Textfield value becomes: `1First`

On the keyboard type: `2`

Textfield value becomes: `21First`

Reproducable on both: device and simulator 
Android version 4.3
Titanium SDK version 3.4.1.GA

**Comment by dbankier** [comment]
Thanks. Will be testing Android soon very soon.

**Comment by dbankier** [comment]
It has to do different behaviour x-platform. Manually setting values on android calls the `change` event. Will work around that.

**Comment by dbankier** [comment]
fixed

**Comment by mpociot** [comment]
Great! Thank you
